### PR TITLE
In extract todo also get schedule, deadline and close date from content (#44)

### PR DESCRIPTION
**Pull request by brvier**
Scheduled Todos don't have schedule date #44 

Not sure that s the right way to do it, i don t understand well your plugin architecture.

### CODE REVIEW

**Comment by dionisos2** [comment]
Hi, I don’t know if it is better or worse, but I also did something like that some time ago :

**Comment by bjonnh** [comment]
This project would really benifit from a rewrite. I agree that this plugin architecture is unneeded and really confusing (even for me). Do you guys have a test file to see which approach works best?

**Comment by dionisos2** [comment]
From what I understand, in the @brvier commit, the `if element.type == SCHEDULED:` should be replaced by `if element.type & SCHEDULED:` to care of case where by example, a item have a schedule and a deadline.

And my commit doesn’t take care of the CLOSED items.

Except for my very specific need, I didn’t test anything.

**Comment by bjonnh** [comment]
Closed as it would be more relevant to use a maintained project such as https://github.com/karlicoss/orgparse .

**Pull request closed without merging**
