### PR TITLE
Fix parsing for tags with "@"

### PR DESCRIPTION
**Pull request by Triagle**
This small pull request allows tags to have "@" or "_" characters as per [the tags documentation](http://orgmode.org/manual/Tags.html) on the orgmode.org website.

Not sure if you want me to add extra test cases for something like this, considering it's such a small change. However I would be happy to add them if required.

### CODE REVIEW

**Comment by bjonnh** [comment]
Hey  @Triagle , do you confirm that @Aurele-Barriere solution works for you? Thanks to you both!

**Comment by Triagle** [comment]
Oh yes, that does in fact work, I've amended the pull request to reflect the recommendations of @Aurele-Barriere.

**Comment by Aurele-Barriere** [comment]
Hi! Could this be merged now? This is a really small change, but it's preventing me from using PyOrgMode.
Thank you.

**Comment by Aurele-Barriere** [comment]
Thanks for the merge :)

**Comment by bjonnh** [comment]
yw! 

Thanks for your help.

**Pull request merged**
